### ISSUE TITLE
Add keys to link between tables

### ISSUE THREAD

**Issue by lwaldron** [seandavi/MungeCuratedMGS#16]
Add a (non-informative) column of unique IDs for each entity, that will go into each table needed as a key. E.g. a "study" key and a "signature" key, where the signature table will include the study key to indicate which study it comes from.

**Comment by lgeistlinger** [comment]
just `seq_len(nrow(toi))` (with `toi` being the table of interest)?

**Comment by lwaldron** [comment]
(I think) they should be unique across tables, say:
```
digest::digest(paste0("studytablekeys", seq_len(nrow(toi))))
```

**Comment by lwaldron** [comment]
The hashing is there to make the point that these keys are not informative and should not be used or modified to encode data. They could even be made one-time-only under the assumption that they are unique to a particular spreadsheet dump, e.g.:
```
digest::digest(paste0("studytablekeys", rnorm(1), seq_len(nrow(toi))))
```

**Comment by lgeistlinger** [comment]
Alright.

Alternatively, could also be of the form 

`paste0(tab.abbrev, seq_len(nrow(toi))))`

where `tab.abbrev` is an abbreviation for each table eg. `LOC` for location, `SIG` for signature, `STUD` for study, etc

and would then result in `LOC1`, `LOC2`, ... for different locations.

**Comment by lwaldron** [comment]
Seems OK to me - the wiki won't end up using the same convention I expect, so these will only be for data transfer and initial setup in any case.

**Comment by lgeistlinger** [comment]
Working on it.
