### ISSUE TITLE
Create matching between NCBI taxon dump and current signature names.

### ISSUE THREAD

**Issue by seandavi** [seandavi/MungeCuratedMGS#17]

**Comment by lgeistlinger** [comment]
Can you elaborate?

Is this just enumerating the NCBI taxa from 1 to _N_ and then use these integers in the signature table to refer to the respective taxa?

**Comment by lwaldron** [comment]
This is referring to NCBI's own IDs which we have a dump of: https://github.com/seandavi/MungeCuratedMGS/blob/5d4c26657069450d2c79d1903dd18161dac44f05/vignettes/data_munging.Rmd#L85

Idea is that, where possible, we would like to use the NCBI taxonomy IDs, which will allow easy linking to NCBI and grabbing of data to display on a microbe's page.

**Comment by lgeistlinger** [comment]
Alright.

**Comment by lwaldron** [comment]
The table should have both our own MetaPhlan names, and NCBI IDs where possible (not all can be mapped to NCBI, these could be left as NA for the NCBI ID).

**Comment by lgeistlinger** [comment]
This is now included as `metaphlan2ncbi.txt` under `inst/extdata` (c8d36bb)
