### ISSUE TITLE
New data model

### ISSUE THREAD

**Issue by lwaldron** [seandavi/MungeCuratedMGS#19]
Ike Hecht's suggestion for a greatly simplified data model:

> Please review the 2 attached CSVs. Please review carefully and see if I got this right.
> 
> I'm using only 2 data structures here. One is for Studies and one is for Signatures. A Study can have multiple Signatures. A Signature can only belong to one Study. (There may be other data structures like "Statistical tests" but I'm leaving those out for now.)
> 
> Essentially, I combined the CSVs you sent as follows:
> 
> Study
> study
> citation
> location
> 
> Signature
> sigmetadata
> contrast
> stat
> signature
> diversity
> 
> The column order doesn't really matter. Note that I changed certain data to suit my purposes (like 16s variable) and I didn't fill in all the "MetaPhlan/NCBI"  data to save time.

[DataModel_2019-12-21.zip](https://github.com/seandavi/MungeCuratedMGS/files/3991502/DataModel_2019-12-21.zip)

**Comment by lwaldron** [comment]
New version:

> Thanks for your patience on yesterday's call. Here is a list of all columns we discussed. Please review it carefully. Please let me know if you have any questions or if anything needs to be changed. Alternatively, if everything looks good, please let me know and we will move forward with creating the structure. Once we move forward, it will be more difficult to change things later.

## Note on coding: 
> I recommend not using the 3-digit (001) format for the page numbers. We will be able to manage a good sort anyway, as you can see here. 

# Study
> study design
> 
> Citation
> PMID
> DOI
> BibTex
> URI
> 
# Experiment
> These fields will all be contained in one page. The heading for each group of fields is in italics.
> 
> Study #
> 
## Subjects
> antibiotics exclusion (multiple)
> location (of subjects) (multiple)
> condition
> Group 0 sample size
> Group 1 sample size
> Group 0 name (part after "vs." in contrast column)
> Group 1 name (part before "vs." in contrast column)
> Group 1 definition ("case definition column")
> condition
> host species
> body_site
> 
## Lab analysis
> sequencing type --> 16s variable region (lower & upper bound)
> sequencing platform
> 
## Statistical Analysis
> statistical test --> LDA Score
> significance threshold
> MHT correction
> matched on
> confounders controlled for
> 
## Diversity Results (increased/decreased/unchanged/unknown: increased means higher diversity in group 1)
> Pielou
> Shannon
> Chao1
> Simpson
> InverseSimpson
> Richness
> 
# Signature
> MetaPhlan, NCBI (multiple sets)
> 
## History
> Experiment #
> source (within publication)
> description
> Association (ex. increased abundance, decreased abundance)
> 
## Credit

> Creation date
> Creation Author
> Revision author
>

**Comment by lgeistlinger** [comment]
The formatting of the above post is not completely clear to me.

How many tables are we supposed to create and which fields should be contained in each of them?

**Comment by lwaldron** [comment]
Sorry I didn't see this right away. It is three tables. I'll do some reformatting of the above to make this clearer.

**Comment by lgeistlinger** [comment]
Done, check c80470e

**Comment by lwaldron** [comment]
@lgeistlinger just add to vignette, so files are produced by vignette.

**Comment by lgeistlinger** [comment]
1. I think we are missing the contrast column above, which seems to belong in the Experiment table (under "Subjects") ?

2. The alpha diversity measures seem to rather belong in the signature table as their values change within an experiment depending whether we are looking at the UP or DOWN signature?

3. It is not completely clear what defines an experiment, ie what makes a study containing more than one experiment. For me the columns under "subjects" and "lab analysis" define an experiment (and can change within a study), whereas the columns under "statistical test" and "results" (the alpha diversity measures) are rather signature-specific (and can change within an experiment).
