### ISSUE TITLE
Add `location` entity

### ISSUE THREAD

**Issue by seandavi** [seandavi/MungeCuratedMGS#3]

**Comment by lgeistlinger** [comment]
I continue working on this one

**Comment by lgeistlinger** [comment]
@lwaldron what's expected here? What we currently annotate in the curation is the _country_ in which the study was carried out. The continent can be inferred. Annotation of city and state / province would require re-curation.

**Comment by lwaldron** [comment]
I think country where the study was carried out is fine. Perhaps we should
perhaps rename it to `studycountry`?

Il ven 6 dic 2019, 9:34 PM lgeistlinger <notifications@github.com> ha
scritto:

**Comment by seandavi** [comment]
This should probably be a many-to-many relationship between study and location.
